version: '3.8'
services:
  mysql:
    image: mysql:8
    command: --mysql-native-password=ON --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "cool"
      MYSQL_USER: "cool"
      MYSQL_PASSWORD: "123123"

  redis:
    image: redis
    restart: always
    environment:
      TZ: Asia/Shanghai
    volumes:
      - redis_data:/data

  chatgpt-api-server:
    image: xyhelper/chatgpt-api-server:latest
    restart: always
    ports:
      - 8100:8001
    environment:
      TZ: Asia/Shanghai
      CHATPROXY: "https://da.xyhelper-agent.com"
      AUTHKEY: "xyhelper"
    volumes:
      - chatgpt_api_data:/app/data
    labels:
      - "com.centurylinklabs.watchtower.scope=xyhelper-chatgpt-api-server"

  xyhelper-web:
    image: xyhelper/xyhelper-web
    restart: always
    ports:
      - 8101:8080
    environment:
      BASE_URI: "http://chatgpt-api-server:8001"
    labels:
      - "com.centurylinklabs.watchtower.scope=xyhelper-chatgpt-api-server"

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --scope xyhelper-chatgpt-api-server --cleanup
    restart: always
    environment:
      TZ: Asia/Shanghai
    labels:
      - "com.centurylinklabs.watchtower.scope=xyhelper-chatgpt-api-server"

volumes:
  mysql_data:
  redis_data:
  chatgpt_api_data:
